/**
 * 页面文案字典（从 Dashboard.tsx 抽出）。
 *
 * 字典属于**数据**而非视图：单独成文件后，Dashboard 与其子组件可以共用
 * 同一份，避免子组件反向依赖页面文件（那会形成循环引用）。
 */

import type { Lang } from '@/i18n';

export const D = {
  zh: {
    page_title: '仪表盘',
    load_failed_title: '加载仪表板失败',
    load_failed_desc: '加载仪表板数据失败',
    btn_retry: '重试',
    welcome_back: '欢迎回来，',
    default_user: '用户',
    workspace_overview: '的工作空间概览',
    btn_invite_members: '邀请成员',
    btn_create_api_key: '创建 API 密钥',
    stat_total_members: '成员总数',
    stat_total_members_sub: '活跃工作空间成员',
    stat_active_api_keys: '活跃 API 密钥',
    stat_active_api_keys_sub: '正在使用的密钥',
    stat_subscription_status: '订阅状态',
    stat_subscription_sub: '当前方案状态',
    stat_days_remaining: '剩余天数',
    stat_days_remaining_sub: '当前计费周期内',
    tabs_aria: '仪表盘分区',
    tab_overview: '概览',
    tab_insights: '数据洞察',
    tab_operations: '运营管理',
    low_stock_title: '库存预警',
    low_stock_count: '个商品库存不足',
    low_stock_more_prefix: '还有',
    low_stock_more_suffix: '个商品...',
    rec_title: '为你推荐',
    rec_subtitle: '基于购买历史的智能推荐',
    weekly_report_title: '周报',
    weekly_report_subtitle: '过去7天运营数据快照',
    week_revenue: '7天营收',
    week_orders: '7天订单',
    aov: '客单价',
    low_stock: '库存预警',
    weekly_schedule_note: '每周一9点自动推送周报邮件',
    btn_send_weekly: '立即发送周报',
    toast_report_sent: '周报已发送',
    toast_report_sent_desc: '周报将发送到工作空间管理员的邮箱',
    toast_send_failed: '发送失败',
    smtp_not_configured: 'SMTP 邮件服务未配置',
    ent_badge_panel: '企业专属面板',
    ai_recommend: 'AI 推荐',
    restock_prefix: '补货 ',
    hot_products_30d: '近30天热销商品',
    no_rec_data: '暂无足够数据生成推荐',
    retention_plan: '召回计划',
    at_risk_customers: '位客户即将流失，建议发送优惠券',
    based_on_rfm: '基于 RFM 客户分层分析',
    optimization_advice: '优化建议',
    aov_value: '客单价',
    aov_unit: '元',
    aov_low_prefix: '，建议设置满',
    aov_low_suffix: '包邮提升客单价',
    aov_good: '，表现良好',
    based_on_sales_data: '基于实际销售数据分析',
    no_data: '暂无数据',
    ai_coverage_title: 'AI分析覆盖',
    profit_rank_title: '单品毛利归因',
    profit_rank_subtitle: '真实成本 × 销量——谁在赚钱，谁在偷利润（近 30 天）',
    pr_margin: '整体毛利率', pr_revenue: '营收', pr_gross: '毛利', pr_loss_sku: '亏损 SKU',
    pr_top: '盈利 Top 5', pr_bottom: '毛利最低 5 项', pr_advice: '经营建议',
    agent_lock_title: '自主巡店 Agent 是 Enterprise 专属',
    agent_lock_hint: '升级后，你的 AI 运营员工每天 9:30 自主当班：发现问题 → 请你确认 → 沉淀经验',
    agent_lock_cta: '升级解锁',
    orders_analyzed: '笔订单参与分析',
    trend_judgment_title: '趋势判断',
    trend_up: '销售呈上升趋势',
    trend_down: '销售呈下降趋势',
    trend_stable: '销售趋势稳定',
    trend_none: '暂无趋势数据',
    order_status_title: '订单状态分布',
    order_status_subtitle: '各状态订单数量占比',
    no_order_data: '暂无订单数据',
    live_events_title: '实时动态',
    live_events_sub: '实时推送中 · 订单 / 退款 / 库存事件',
    live_events_offline: '连接中…',
    live_events_empty: '暂无实时事件',
    live_events_empty_desc: '在收款页发起一笔支付，事件将实时出现在这里。',
    no_order_data_desc: '还没有订单数据，创建订单后即可查看',
    pro_dashboard: 'Pro 仪表盘',
    sales_trend_title: '销售趋势',
    sales_trend_subtitle: '最近30天销售数据',
    no_sales_data: '暂无销售数据',
    no_sales_data_desc: '还没有销售趋势数据',
    customer_value_title: '客户价值分析',
    customer_value_subtitle: '基于RFM模型的客户分层',
    no_customer_segments: '还没有客户分群数据',
    membership_title: '会员等级分布',
    membership_subtitle: '客户等级统计',
    membership_total_prefix: '共',
    membership_total_suffix: ' 位客户',
    loading: '加载中...',
    no_customer_data: '暂无客户数据',
    unknown: '未知',
    svc_perf_title: '服务性能',
    svc_perf_subtitle: '实时服务器资源使用情况',
    memory_usage: '内存使用',
    cpu_usage: 'CPU 使用率',
    active_connections: '活动连接',
    quick_actions_title: '快速操作',
    qa_invite: '邀请成员',
    qa_create_key: '创建 API 密钥',
    qa_workspace_settings: '工作空间设置',
    qa_view_analytics: '查看分析',
    recent_activity_title: '最近动态',
    recent_activity_subtitle: '工作空间中的最新操作',
    activity_by_prefix: '由',
    activity_by_suffix: ' 操作',
    no_recent_activity: '暂无最近动态。',
    st_active: '活跃',
    st_trialing: '试用中',
    st_past_due: '逾期',
    st_cancelled: '已取消',
    st_incomplete: '待支付',
    st_unknown: '未知',
    st_pending: '待确认',
    st_confirmed: '已确认',
    st_processing: '处理中',
    st_shipped: '已发货',
    st_delivered: '已签收',
    st_refunded: '已退款',
  },
  en: {
    page_title: 'Dashboard',
    load_failed_title: 'Failed to load dashboard',
    load_failed_desc: 'Failed to load dashboard data',
    btn_retry: 'Retry',
    welcome_back: 'Welcome back, ',
    default_user: 'user',
    workspace_overview: ' workspace overview',
    btn_invite_members: 'Invite members',
    btn_create_api_key: 'Create API key',
    stat_total_members: 'Total members',
    stat_total_members_sub: 'Active workspace members',
    stat_active_api_keys: 'Active API keys',
    stat_active_api_keys_sub: 'Keys in use',
    stat_subscription_status: 'Subscription',
    stat_subscription_sub: 'Current plan status',
    stat_days_remaining: 'Days remaining',
    stat_days_remaining_sub: 'In current billing period',
    tabs_aria: 'Dashboard sections',
    tab_overview: 'Overview',
    tab_insights: 'Insights',
    tab_operations: 'Operations',
    low_stock_title: 'Low stock alert',
    low_stock_count: 'products below threshold',
    low_stock_more_prefix: '+',
    low_stock_more_suffix: 'more items...',
    rec_title: 'Recommended for you',
    rec_subtitle: 'Smart recommendations based on purchase history',
    weekly_report_title: 'Weekly report',
    weekly_report_subtitle: 'Last 7 days operations snapshot',
    week_revenue: '7d revenue',
    week_orders: '7d orders',
    aov: 'AOV',
    low_stock: 'Low stock',
    weekly_schedule_note: 'Weekly report is emailed automatically every Monday at 8:00 AM',
    btn_send_weekly: 'Send now',
    toast_report_sent: 'Weekly report sent',
    toast_report_sent_desc: 'The report will be emailed to workspace admins',
    toast_send_failed: 'Send failed',
    smtp_not_configured: 'SMTP email service is not configured',
    ent_badge_panel: 'Enterprise Panel',
    ai_recommend: 'AI Recommend',
    restock_prefix: 'Restock ',
    hot_products_30d: 'Top seller in the last 30 days',
    no_rec_data: 'Not enough data to generate recommendations',
    retention_plan: 'Retention plan',
    at_risk_customers: 'customers are at risk of churning — send coupons',
    based_on_rfm: 'Based on RFM customer segmentation',
    optimization_advice: 'Optimization advice',
    aov_value: 'AOV ',
    aov_unit: '',
    aov_low_prefix: ', set free shipping at ¥',
    aov_low_suffix: ' to boost AOV',
    aov_good: ', performing well',
    based_on_sales_data: 'Based on actual sales data',
    no_data: 'No data',
    ai_coverage_title: 'AI Analysis Coverage',
    profit_rank_title: 'Per-Product Margin Attribution',
    profit_rank_subtitle: 'Real cost x sales - who earns, who leaks profit (30d)',
    pr_margin: 'Overall margin', pr_revenue: 'Revenue', pr_gross: 'Gross profit', pr_loss_sku: 'Loss SKUs',
    pr_top: 'Top 5 margin', pr_bottom: 'Lowest 5 margin', pr_advice: 'Recommendations',
    agent_lock_title: 'Store Sentinel Agent is Enterprise-only',
    agent_lock_hint: 'Upgrade so your AI operator patrols daily at 9:30: finds issues → asks you → learns',
    agent_lock_cta: 'Upgrade',
    orders_analyzed: 'orders analyzed',
    trend_judgment_title: 'Trend',
    trend_up: 'Sales are trending upward',
    trend_down: 'Sales are trending downward',
    trend_stable: 'Sales trend is stable',
    trend_none: 'No trend data yet',
    order_status_title: 'Order status distribution',
    order_status_subtitle: 'Order share by status',
    no_order_data: 'No order data',
    live_events_title: 'Live events',
    live_events_sub: 'Streaming in real time · orders / refunds / stock',
    live_events_offline: 'Connecting…',
    live_events_empty: 'No live events yet',
    live_events_empty_desc: 'Start a payment on the Payments page and events will stream in here.',
    no_order_data_desc: 'No orders yet — create an order to see it here',
    pro_dashboard: 'Pro Dashboard',
    sales_trend_title: 'Sales trend',
    sales_trend_subtitle: 'Last 30 days sales data',
    no_sales_data: 'No sales data',
    no_sales_data_desc: 'No sales trend data yet',
    customer_value_title: 'Customer value analysis',
    customer_value_subtitle: 'RFM-based customer segments',
    no_customer_segments: 'No customer segment data yet',
    membership_title: 'Membership distribution',
    membership_subtitle: 'Customer level statistics',
    membership_total_prefix: 'Total ',
    membership_total_suffix: ' customers',
    loading: 'Loading...',
    no_customer_data: 'No customer data',
    unknown: 'Unknown',
    svc_perf_title: 'Service performance',
    svc_perf_subtitle: 'Real-time server resource usage',
    memory_usage: 'Memory usage',
    cpu_usage: 'CPU usage',
    active_connections: 'Active connections',
    quick_actions_title: 'Quick actions',
    qa_invite: 'Invite members',
    qa_create_key: 'Create API key',
    qa_workspace_settings: 'Workspace settings',
    qa_view_analytics: 'View analytics',
    recent_activity_title: 'Recent activity',
    recent_activity_subtitle: 'Latest actions in the workspace',
    activity_by_prefix: 'By',
    activity_by_suffix: '',
    no_recent_activity: 'No recent activity.',
    st_active: 'Active',
    st_trialing: 'Trialing',
    st_past_due: 'Past due',
    st_cancelled: 'Cancelled',
    st_incomplete: 'Incomplete',
    st_unknown: 'Unknown',
    st_pending: 'Pending',
    st_confirmed: 'Confirmed',
    st_processing: 'Processing',
    st_shipped: 'Shipped',
    st_delivered: 'Delivered',
    st_refunded: 'Refunded',
  },
} as Record<Lang, Record<string, string>>;
