"""Nexora - Natural Language BI Assistant (AI Agent).

Answers business questions in Chinese by:

1. Detecting the user's intent with lightweight keyword rules (no external
   API required for basic operation);
2. Querying the actual database (Order / OrderItem / Product / Refund /
   Customer) scoped to the workspace via SQLAlchemy;
3. Returning a structured dict the frontend renders as text + data table +
   simple chart, together with an actionable suggestion.

When ``settings.QWEN_API_KEY`` is configured, the rule-based answer is
upgraded with a natural-language response generated by Qwen (通义千问).
Any failure while calling Qwen falls back to the deterministic rule-based
answer so the endpoint always returns something useful.
"""

import json
from datetime import datetime, timedelta, timezone
from typing import Any

import httpx
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.customer import Customer
from app.models.order import Order, OrderItem, OrderStatus
from app.models.product import Product
from app.models.refund import Refund, RefundStatus
from app.utils.logging import get_logger

logger = get_logger(__name__)

# DashScope non-compatible mode text-generation endpoint.
_QWEN_GENERATION_URL = (
    "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
)

# Order statuses excluded from "valid" revenue / order statistics.
_EXCLUDED_STATUSES = [OrderStatus.CANCELLED, OrderStatus.REFUNDED]


def _money(value: float) -> str:
    """Format a monetary value as ¥ with 2 decimals."""
    return f"¥{value:,.2f}"


def _round2(value: float) -> float:
    """Round a float to 2 decimal places."""
    return round(value, 2)


async def _call_qwen_generation(
    system: str, prompt: str, temperature: float = 0.5
) -> str | None:
    """Call the Qwen text-generation API.

    Returns the assistant's text content, or ``None`` when no API key is
    configured / the request fails, so callers can fall back to rule-based
    output.
    """
    key = settings.QWEN_API_KEY
    if not key:
        return None

    payload = {
        "model": settings.QWEN_MODEL,
        "input": {
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ]
        },
        "parameters": {"temperature": temperature, "result_format": "message"},
    }
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                _QWEN_GENERATION_URL,
                headers={
                    "Authorization": f"Bearer {key}",
                    "Content-Type": "application/json",
                },
                json=payload,
            )
            data = resp.json()
            if resp.status_code != 200:
                logger.warning(
                    "Qwen generation failed (%s): %s", resp.status_code, data
                )
                return None
            content = (
                data.get("output", {})
                .get("choices", [{}])[0]
                .get("message", {})
                .get("content")
            )
            if not content:
                content = data.get("output", {}).get("text")
            return content.strip() if content else None
    except Exception as e:  # noqa: BLE001 - deliberate broad fallback
        logger.warning("Qwen generation call failed: %s", e)
        return None


class BIAgent:
    """BI agent that answers business questions from the real database."""

    # Intent detection keywords. Order matters: more specific intents are
    # checked first so e.g. "退款率高的订单" resolves to refund_rate, not
    # order_count.
    INTENT_KEYWORDS: dict[str, tuple[str, ...]] = {
        "churn_customers": ("流失", "沉睡", "未复购", "没再买", "很久没买", "不活跃", "唤回", "唤醒"),
        "refund_rate": ("退款", "退货", "退单", "退款率", "退货率"),
        "top_products": ("卖得最好", "爆款", "top", "最畅销", "热销", "销售排行", "销量最高", "卖得最多", "买得最多", "买的最多", "购买最多"),
        "low_stock": ("库存不足", "缺货", "预警", "库存告急", "快卖完", "补货", "库存低"),
        "product_list": ("有哪些商品", "商品列表", "什么商品", "商品清单", "产品列表", "商品有哪些", "看看商品", "商品都有"),
        "order_list": ("最近订单", "订单列表", "订单明细", "最新订单", "看看订单", "有哪些订单"),
        "refund_list": ("退款列表", "退款记录", "有哪些退款", "看看退款"),
        "customer_list": ("有哪些客户", "客户列表", "客户名单", "看看客户"),
        "customer_insight": ("复购", "回头客", "会员", "客户分析", "客户画像"),
        "revenue_summary": ("营收", "收入", "销售额", "卖了多少钱", "赚了多少", "营业额", "gmv", "卖了"),
        "order_count": ("多少单", "单量", "下单量", "几单", "订单数", "订单"),
    }

    # ------------------------------------------------------------------
    # Intent parsing
    # ------------------------------------------------------------------

    @staticmethod
    def detect_intent(question: str) -> str:
        """Map a free-text question to a known BI intent (keyword rules)."""
        q = question.lower()
        for intent, keywords in BIAgent.INTENT_KEYWORDS.items():
            if any(k in q for k in keywords):
                return intent
        return "default"

    # ------------------------------------------------------------------
    # Natural-language enhancement (Qwen, optional)
    # ------------------------------------------------------------------

    @staticmethod
    async def _enhance_answer(
        question: str,
        result: dict[str, Any],
        history: list[dict] | None = None,
    ) -> str | None:
        """Ask Qwen to phrase a natural answer over the query results."""
        data_json = json.dumps(result.get("data", []), ensure_ascii=False)
        snapshot_json = json.dumps(result.get("snapshot", {}), ensure_ascii=False)
        history_text = ""
        if history:
            lines = []
            for msg in history[-6:]:
                role = "用户" if msg.get("role") == "user" else "助手"
                lines.append(f"{role}：{str(msg.get('content', ''))[:300]}")
            history_text = "以下是本次会话的历史对话（供上下文参考）：\n" + "\n".join(lines) + "\n\n"
        prompt = (
            f"商家问题：{question}\n\n"
            f"{history_text}"
            f"以下是系统已从数据库查询到的真实数据（JSON）：\n{data_json}\n\n"
            f"以下是该工作空间的整体经营快照（JSON）：\n{snapshot_json}\n\n"
            "请优先基于以上真实数据回答。如果查询结果为空，可结合经营快照回答。"
            "若用户的问题与历史对话相关（如\"那退款呢\"\"刚才说的那个\"），请结合历史上下文理解。"
            "用简洁、专业的中文，不要编造数据，只输出回答本身。"
        )
        return await _call_qwen_generation(
            "你是一位专业的电商数据分析助手，回答要简洁、准确、口语化。",
            prompt,
            temperature=0.5,
        )

    # ------------------------------------------------------------------
    # Intent handlers (each returns the rule-based result dict)
    # ------------------------------------------------------------------

    @staticmethod
    async def _revenue_summary(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        now = datetime.now(timezone.utc)
        month_start = datetime(now.year, now.month, 1, tzinfo=timezone.utc)

        result = await db.execute(
            select(Order).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
                Order.created_at >= month_start,
            )
        )
        orders = result.scalars().all()

        total_revenue = sum(float(o.total or 0) for o in orders)
        daily: dict[str, float] = {}
        for o in orders:
            if o.created_at is not None:
                key = o.created_at.date().isoformat()
                daily[key] = daily.get(key, 0.0) + float(o.total or 0)

        # Build a continuous daily series from month start up to today.
        series = []
        for day in range(1, now.day + 1):
            date_str = f"{now.year:04d}-{now.month:02d}-{day:02d}"
            series.append({
                "label": f"{now.month}月{day}日",
                "value": _round2(daily.get(date_str, 0.0)),
            })

        answer = (
            f"本月（{now.year}年{now.month}月）营收 {_money(total_revenue)}，"
            f"共 {len(orders)} 笔有效订单。"
        )
        return {
            "intent": "revenue_summary",
            "answer_text": answer,
            "data": series,
            "chart_type": "line",
            "suggestion": (
                "建议对比上月同期数据，重点关注热销商品与转化率变化，"
                "及时发现增长或下滑趋势。"
            ),
        }

    @staticmethod
    async def _order_count(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        now = datetime.now(timezone.utc)
        today_start = datetime(now.year, now.month, now.day, tzinfo=timezone.utc)
        month_start = datetime(now.year, now.month, 1, tzinfo=timezone.utc)

        total = await db.scalar(
            select(func.count(Order.id)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
        )
        month = await db.scalar(
            select(func.count(Order.id)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
                Order.created_at >= month_start,
            )
        )
        today = await db.scalar(
            select(func.count(Order.id)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
                Order.created_at >= today_start,
            )
        )
        total = int(total or 0)
        month = int(month or 0)
        today = int(today or 0)

        return {
            "intent": "order_count",
            "answer_text": (
                f"当前累计有效订单 {total} 笔；本月新增 {month} 笔，今日 {today} 笔。"
            ),
            "data": [
                {"label": "累计有效订单", "value": total},
                {"label": "本月订单", "value": month},
                {"label": "今日订单", "value": today},
            ],
            "chart_type": "number",
            "suggestion": (
                "若今日订单明显低于近期均值，建议检查流量渠道与促销活动效果。"
            ),
        }

    @staticmethod
    async def _refund_rate(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        refund_count = await db.scalar(
            select(func.count(Refund.id)).where(
                Refund.workspace_id == workspace_id,
                Refund.status.in_([RefundStatus.APPROVED, RefundStatus.COMPLETED]),
            )
        )
        total_orders = await db.scalar(
            select(func.count(Order.id)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
        )
        refund_count = int(refund_count or 0)
        total_orders = int(total_orders or 0)
        rate = round(refund_count / total_orders * 100, 1) if total_orders else 0.0

        return {
            "intent": "refund_rate",
            "answer_text": (
                f"退款订单 {refund_count} 笔，占全部 {total_orders} 笔有效订单的 {rate:.1f}%。"
            ),
            "data": [
                {"label": "退款订单数", "value": refund_count},
                {"label": "总订单数", "value": total_orders},
                {"label": "退款率", "value": f"{rate:.1f}%"},
            ],
            "chart_type": "number",
            "suggestion": (
                "若退款率超过 5%，建议优先排查商品质量与物流时效问题，"
                "并对高频退款商品做下架或改进处理。"
            ),
        }

    @staticmethod
    async def _top_products(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        result = await db.execute(
            select(
                Product.name,
                func.sum(OrderItem.quantity),
                func.sum(OrderItem.total_price),
            )
            .join(OrderItem, OrderItem.product_id == Product.id)
            .join(Order, Order.id == OrderItem.order_id)
            .where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
            .group_by(Product.id, Product.name)
            .order_by(func.sum(OrderItem.quantity).desc())
            .limit(5)
        )
        rows = result.all()
        data = [
            {
                "name": name,
                "value": int(quantity or 0),
                "revenue": _round2(float(revenue or 0)),
            }
            for name, quantity, revenue in rows
        ]

        if not data:
            answer = "暂无可统计的热销商品，建议先完善商品与订单数据。"
        else:
            top = data[0]
            answer = (
                f"热销商品 Top {len(data)}：榜首「{top['name']}」销量 {top['value']} 件，"
                f"销售额 {_money(top['revenue'])}。"
            )

        return {
            "intent": "top_products",
            "answer_text": answer,
            "data": data,
            "chart_type": "bar",
            "suggestion": (
                "为热销商品及时补货并优化详情页，可搭配套餐或满减提升客单价。"
            ),
        }

    @staticmethod
    async def _low_stock(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        result = await db.execute(
            select(Product)
            .where(
                Product.workspace_id == workspace_id,
                Product.stock <= Product.low_stock_threshold,
            )
            .order_by(Product.stock.asc())
            .limit(10)
        )
        products = result.scalars().all()
        data = [
            {
                "name": p.name,
                "stock": p.stock,
                "threshold": p.low_stock_threshold,
            }
            for p in products
        ]

        if not data:
            answer = "当前没有库存不足的商品，库存状况良好。"
        else:
            names = "、".join(p["name"] for p in data[:5])
            answer = (
                f"当前有 {len(data)} 个商品库存低于预警线：{names}。"
                if len(data) <= 5
                else f"当前有 {len(data)} 个商品库存低于预警线，前 5 个为：{names}。"
            )

        return {
            "intent": "low_stock",
            "answer_text": answer,
            "data": data,
            "chart_type": "list",
            "suggestion": (
                "建议优先为销量稳定但库存不足的商品安排补货，避免断货损失销售。"
            ),
        }

    @staticmethod
    async def _customer_insight(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        now = datetime.now(timezone.utc)
        result = await db.execute(
            select(Customer).where(Customer.workspace_id == workspace_id)
        )
        customers = result.scalars().all()
        total = len(customers)
        repeat = sum(1 for c in customers if c.total_orders >= 2)
        churned = sum(
            1
            for c in customers
            if c.last_order_at is not None and (now - c.last_order_at).days > 90
        )

        repeat_pct = round(repeat / total * 100, 1) if total else 0.0
        answer = (
            f"当前共有客户 {total} 人，其中复购客户（≥2 单）{repeat} 人，"
            f"占比 {repeat_pct:.1f}%；超过 90 天未下单的潜在流失客户 {churned} 人。"
        )
        return {
            "intent": "customer_insight",
            "answer_text": answer,
            "data": [
                {"name": "总客户", "value": total},
                {"name": "复购客户", "value": repeat},
                {"name": "潜在流失", "value": churned},
            ],
            "chart_type": "bar",
            "suggestion": (
                "对潜在流失客户发送唤醒优惠券，对复购客户建立会员权益，"
                "提升客户终身价值。"
            ),
        }

    @staticmethod
    async def _overview(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        total_revenue = await db.scalar(
            select(func.sum(Order.total)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
        )
        total_orders = await db.scalar(
            select(func.count(Order.id)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
        )
        refund_count = await db.scalar(
            select(func.count(Refund.id)).where(
                Refund.workspace_id == workspace_id,
                Refund.status.in_([RefundStatus.APPROVED, RefundStatus.COMPLETED]),
            )
        )
        low_stock_count = await db.scalar(
            select(func.count(Product.id)).where(
                Product.workspace_id == workspace_id,
                Product.stock <= Product.low_stock_threshold,
            )
        )
        total_revenue = float(total_revenue or 0)
        total_orders = int(total_orders or 0)
        refund_count = int(refund_count or 0)
        low_stock_count = int(low_stock_count or 0)
        rate = round(refund_count / total_orders * 100, 1) if total_orders else 0.0

        answer = (
            f"店铺概览：累计营收 {_money(total_revenue)}，有效订单 {total_orders} 笔，"
            f"退款率 {rate:.1f}%，{low_stock_count} 个商品需要补货。"
        )
        return {
            "intent": "default",
            "answer_text": answer,
            "data": [
                {"label": "累计营收", "value": f"¥{total_revenue:,.2f}"},
                {"label": "有效订单", "value": total_orders},
                {"label": "退款率", "value": f"{rate:.1f}%"},
                {"label": "库存预警", "value": low_stock_count},
            ],
            "chart_type": "number",
            "suggestion": (
                "建议定期查看营收与退款率变化，及时调整商品结构与营销策略。"
            ),
        }

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @staticmethod
    async def intent_data(
        db: AsyncSession, workspace_id: str, question: str
    ) -> dict[str, Any]:
        """Run intent detection + real DB query, return the raw result dict.

        Unlike ``answer()`` this performs NO Qwen enhancement — it returns
        the pure query result so callers (e.g. streaming chat) can embed the
        real data into their own LLM context.
        """
        intent = BIAgent.detect_intent(question)

        handlers = {
            "revenue_summary": BIAgent._revenue_summary,
            "order_count": BIAgent._order_count,
            "refund_rate": BIAgent._refund_rate,
            "top_products": BIAgent._top_products,
            "low_stock": BIAgent._low_stock,
            "churn_customers": BIAgent._churn_customers,
            "customer_insight": BIAgent._customer_insight,
            "product_list": BIAgent._product_list,
            "order_list": BIAgent._order_list,
            "refund_list": BIAgent._refund_list,
            "customer_list": BIAgent._customer_list,
            "default": BIAgent._overview,
        }
        result = await handlers[intent](db, workspace_id)
        result["intent"] = intent
        # 附带全站快照，让 AI 对未命中的问题也有真实数据兜底
        try:
            result["snapshot"] = await BIAgent._workspace_snapshot(db, workspace_id)
        except Exception:
            result["snapshot"] = {}
        return result


    @staticmethod
    async def _product_list(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        """List the workspace's products with price/stock."""
        rows = (
            await db.execute(
                select(Product)
                .where(Product.workspace_id == workspace_id)
                .order_by(Product.created_at.desc())
                .limit(50)
            )
        ).scalars().all()
        data = [
            {
                "name": p.name,
                "price": float(p.price or 0),
                "stock": p.stock,
                "category": p.category or "",
                "status": str(p.status),
            }
            for p in rows
        ]
        return {
            "answer_text": f"当前工作空间共有 {len(data)} 个商品。",
            "data": data,
            "chart_type": "list",
            "suggestion": "可前往商品管理查看完整列表与编辑。",
        }

    @staticmethod
    async def _order_list(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        """List the most recent orders."""
        rows = (
            await db.execute(
                select(Order)
                .where(Order.workspace_id == workspace_id)
                .order_by(Order.created_at.desc())
                .limit(20)
            )
        ).scalars().all()
        data = [
            {
                "order_number": o.order_number,
                "customer": o.customer_name or "Walk-in",
                "total": _round2(float(o.total or 0)),
                "status": str(o.status),
                "payment_status": str(o.payment_status),
                "date": o.created_at.isoformat() if o.created_at else None,
            }
            for o in rows
        ]
        return {
            "answer_text": f"最近共 {len(data)} 笔订单。",
            "data": data,
            "chart_type": "list",
            "suggestion": "可前往订单管理查看全部订单。",
        }

    @staticmethod
    async def _refund_list(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        """List the most recent refunds."""
        rows = (
            await db.execute(
                select(Refund)
                .where(Refund.workspace_id == workspace_id)
                .order_by(Refund.created_at.desc())
                .limit(20)
            )
        ).scalars().all()
        data = [
            {
                "id": str(r.id)[:8],
                "amount": _round2(float(r.amount or 0)),
                "reason": (r.reason or "")[:50],
                "status": str(r.status),
                "date": r.created_at.isoformat() if r.created_at else None,
            }
            for r in rows
        ]
        return {
            "answer_text": f"最近共 {len(data)} 笔退款记录。",
            "data": data,
            "chart_type": "list",
            "suggestion": "可前往退款售后查看详情。",
        }

    @staticmethod
    async def _churn_customers(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        """流失预警：最近 30 天未复购的客户（真实查库）。"""
        from datetime import datetime, timezone, timedelta
        from sqlalchemy import or_

        cutoff = datetime.now(timezone.utc) - timedelta(days=30)
        rows = (
            await db.execute(
                select(Customer)
                .where(
                    Customer.workspace_id == workspace_id,
                    or_(
                        Customer.last_order_at.is_(None),
                        Customer.last_order_at < cutoff,
                    ),
                )
                .order_by(Customer.last_order_at.asc().nulls_last())
                .limit(30)
            )
        ).scalars().all()

        data = [
            {
                "name": c.name,
                "email": c.email or "",
                "orders": c.total_orders,
                "spent": round(float(c.total_spent or 0), 2),
                "last_order": c.last_order_at.strftime("%Y-%m-%d") if c.last_order_at else "从未下单",
            }
            for c in rows
        ]
        churned = len(data)
        answer = (
            f"当前有 {churned} 位客户超过 30 天未复购（含从未下单），"
            "建议对名单中的客户发送唤醒优惠。"
        )
        return {
            "intent": "churn_customers",
            "answer_text": answer,
            "data": data,
            "chart_type": "list",
            "suggestion": (
                "对 30 天未复购客户发放唤醒券（如满 99 减 20），"
                "并按消费金额排序优先触达高价值客户。"
            ),
        }

    @staticmethod
    async def _customer_list(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        """List the workspace's customers."""
        rows = (
            await db.execute(
                select(Customer)
                .where(Customer.workspace_id == workspace_id)
                .order_by(Customer.created_at.desc())
                .limit(30)
            )
        ).scalars().all()
        data = [
            {
                "name": c.name,
                "email": c.email or "",
                "level": str(c.membership_level),
                "tags": c.tags or [],
            }
            for c in rows
        ]
        return {
            "answer_text": f"当前共 {len(data)} 位客户。",
            "data": data,
            "chart_type": "list",
            "suggestion": "可前往客户 CRM 查看 RFM 分层。",
        }

    @staticmethod
    async def _workspace_snapshot(db: AsyncSession, workspace_id: str) -> dict[str, Any]:
        """A compact overview of the workspace — used as AI grounding fallback."""
        now = datetime.now(timezone.utc)
        total_products = await db.scalar(
            select(func.count(Product.id)).where(Product.workspace_id == workspace_id)
        ) or 0
        total_orders = await db.scalar(
            select(func.count(Order.id)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
        ) or 0
        total_customers = await db.scalar(
            select(func.count(Customer.id)).where(Customer.workspace_id == workspace_id)
        ) or 0
        refund_count = await db.scalar(
            select(func.count(Refund.id)).where(Refund.workspace_id == workspace_id)
        ) or 0
        revenue_30d = await db.scalar(
            select(func.sum(Order.total)).where(
                Order.workspace_id == workspace_id,
                Order.status.notin_(_EXCLUDED_STATUSES),
                Order.created_at >= now - timedelta(days=30),
            )
        ) or 0
        low_stock_count = await db.scalar(
            select(func.count(Product.id)).where(
                Product.workspace_id == workspace_id,
                Product.stock <= Product.low_stock_threshold,
            )
        ) or 0
        return {
            "total_products": total_products,
            "total_orders": total_orders,
            "total_customers": total_customers,
            "refund_count": refund_count,
            "revenue_last_30d": _round2(float(revenue_30d)),
            "low_stock_count": low_stock_count,
        }

    @staticmethod
    async def answer(
        db: AsyncSession,
        workspace_id: str,
        user_id: str,
        question: str,
        history: list[dict] | None = None,
    ) -> dict[str, Any]:
        """Answer a natural-language business question.

        Args:
            db: Async database session.
            workspace_id: Workspace scope for all queries.
            user_id: Calling user (used for future audit / personalization).
            question: The user's free-text question in Chinese.
            history: Optional recent chat history for multi-turn context.

        Returns:
            A dict with ``intent``, ``answer_text``, ``data``, ``chart_type``
            and ``suggestion`` ready for the frontend to render.
        """
        result = await BIAgent.intent_data(db, workspace_id, question)

        # Optional Qwen natural-language upgrade; always fall back on failure.
        if settings.QWEN_API_KEY:
            ai_text = await BIAgent._enhance_answer(question, result, history)
            if ai_text:
                result["answer_text"] = ai_text

        return result

    @staticmethod
    async def pricing_suggestion(
        db: AsyncSession, workspace_id: str
    ) -> list[dict[str, Any]]:
        """Suggest pricing actions per product based on stock coverage.

        Computes average daily sales over the last 30 days, then
        days-of-cover = stock / avg_daily:
            - < 15 days  -> suggest a 5-10% discount to clear stock
            - > 60 days  -> suggest a 3-5% price increase
            - otherwise  -> keep the current price
        Products with no sales in the window are treated as overstocked.

        Returns:
            A list of ``{product_id, name, current_price, suggestion, reason}``.
        """
        now = datetime.now(timezone.utc)
        days_ago = now - timedelta(days=30)

        products_result = await db.execute(
            select(Product).where(Product.workspace_id == workspace_id)
        )
        products = products_result.scalars().all()

        # Single aggregated query for the last 30 days (avoids N+1).
        qty_result = await db.execute(
            select(OrderItem.product_id, func.sum(OrderItem.quantity))
            .join(Order, Order.id == OrderItem.order_id)
            .where(
                OrderItem.product_id.isnot(None),
                Order.workspace_id == workspace_id,
                Order.created_at >= days_ago,
                Order.status.notin_(_EXCLUDED_STATUSES),
            )
            .group_by(OrderItem.product_id)
        )
        qty_map = dict(qty_result.all())

        suggestions: list[dict[str, Any]] = []
        for product in products:
            sold_qty = int(qty_map.get(product.id, 0) or 0)
            avg_daily = sold_qty / 30
            price = float(product.price or 0)

            if avg_daily <= 0:
                suggestion = "促销"
                reason = "近30天无销量，建议降价5%-10%吸引用户、加快周转"
            else:
                days_of_cover = product.stock / avg_daily
                if days_of_cover < 15:
                    suggestion = "促销"
                    reason = (
                        f"当前库存仅够销售约 {days_of_cover:.0f} 天，"
                        "建议降价5%-10%加快清库存"
                    )
                elif days_of_cover > 60:
                    suggestion = "涨价"
                    reason = (
                        f"当前库存可支撑约 {days_of_cover:.0f} 天，"
                        "供不应求，建议上调价格3%-5%"
                    )
                else:
                    suggestion = "保持"
                    reason = (
                        f"库存可支撑约 {days_of_cover:.0f} 天，供需均衡，"
                        "建议维持现价并观察趋势"
                    )

            suggestions.append({
                "product_id": product.id,
                "name": product.name,
                "current_price": _round2(price),
                "suggestion": suggestion,
                "reason": reason,
            })

        return suggestions
