"""add agent_experiences knowledge base table

Revision ID: eda0f99c71f8
Revises: 97baf56a92f2
Create Date: 2026-09-04 20:14:15.904329
"""
from alembic import op
import sqlalchemy as sa


revision = 'eda0f99c71f8'
down_revision = '97baf56a92f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_experiences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('insight_id', sa.String(length=36), nullable=True),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('result_before', sa.Float(), nullable=True),
    sa.Column('result_after', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('delta_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['ai_insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_experiences_workspace_id'), 'agent_experiences', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_experiences_workspace_id'), table_name='agent_experiences')
    op.drop_table('agent_experiences')
    # ### end Alembic commands ###
